#!/usr/bin/env python

status_dict = {
    1: 'SearchingForParkingSlotRightParallel',
    2: 'SearchingForParkingSlotLeftParallel',
    3: 'SearchingForParkingSlotRightParallelPerp1',
    4: 'SearchingForParkingSlotLeftParallelPerp1',
    5: 'LimitDriveSpeed',
    6: 'AutoSteeringActivated',
    7: 'AutoSteeringActivatedREABOff',
    8: 'ParkingCompleted',
    9: 'ParallelParkingRight',
    10: 'ParallelParkingRightProgressForward',
    11: 'ParallelParkingRightProgressBackward',
    12: 'ParallelParkingRightStop',
    13: 'ParallelParkingLeft',
    14: 'ParallelParkingLeftProgressForward',
    15: 'ParallelParkingLeftProgressBackward',
    16: 'ParallelParkingLeftStop',
    17: 'SearchingForParkingSlotRightPerp1',
    18: 'SearchingForParkingSlotLeftPerp1',
    19: 'PerpendicularParkingRight',
    20: 'PerpendicularParkingRightProgress',
    21: 'PerpendicularParkingRightStop',
    22: 'PerpendicularParkingLeft',
    23: 'PerpendicularParkingLeftProgress',
    24: 'PerpendicularParkingLeftStop',
    25: 'ParkingFailed',
    26: 'Cancel',
    27: 'UnparkRight',
    28: 'UnparkLeft',
    29: 'ParkExitFail',
    30: 'ParkExitCompleted',
    31: 'ParkMovesExceeded',
    32: 'OverSpeed',
    33: 'DriveInterference',
    34: 'CheckOwnerManual',
    35: 'ParkingSpaceFoundRightParallel',
    36: 'ParkingSpaceFoundLeftParallel',
    37: 'ParkingSpaceFoundRightPerp',
    38: 'ParkingSpaceFoundLeftPerp',
    39: 'MoveAheadRightParallel',
    40: 'MoveAheadLeftParallel',
    41: 'MoveAheadRightPerp',
    42: 'MoveAheadLeftPerp'
}

status_str_dict = {
    1: 'Searching for parallel parking space on right.',
    2: 'Searching for parallel parking space on left.',
    3: 'Searching for parallel parking space on right.',
    4: 'Searching for parallel parking space on left.',
    5: 'approaching maximum speed.',
    6: 'Automatic Steering On - be prepared to brake.',
    7: 'Automatic Steering On - emergency braking off.',
    8: 'Complete - take control.',
    9: 'Stop and shift to Reverse.',
    10: 'Drive forward slowly - be prepared to brake.',
    11: 'Back up slowly - be prepared to brake.',
    12: 'Stop',
    13: 'Stop and shift to Reverse.',
    14: 'Drive forward slowly - be prepared to brake.',
    15: 'Back up slowly - be prepared to brake.',
    16: 'Stop',
    17: 'Searching for perpendicular parking space on right.',
    18: 'Searching for perpendicular parking space on left.',
    19: 'Stop and shift to Reverse.',
    20: 'Drive forward slowly - be prepared to brake.',
    21: 'Stop',
    22: 'Stop and shift to Reverse.',
    23: 'Drive forward slowly - be prepared to brake.',
    24: 'Stop',
    25: 'Canceled - see Owner\'s Manual.',
    26: 'Deactivated',
    27: 'Exit parking space to left. Shift to Reverse to begin.',
    28: 'Exit parking space to right. Shift to Reverse to begin.',
    29: 'Canceled',
    30: 'Complete - take control.',
    31: '''Canceled - can't park in this space.''',
    32: 'Canceled - overspeed.',
    33: 'Canceled - driver interference.',
    34: 'Canceled - see Owner\'s Manual.',
    35: 'space found on right.',
    36: 'space found on left.',
    37: 'space found on right.',
    38: 'space found on left.',
    39: 'Drive forward.',
    40: 'Drive forward.',
    41: 'Drive forward.',
    42: 'Drive forward.'
}


def get_APA_status():
    return status_dict


def get_APA_status_string():
    return status_str_dict
